fail_fast: true
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/jorisroovers/gitlint.git
    rev: v0.19.1
    hooks:
      - id: gitlint
  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v18.1.8
  #   hooks:
  #     - id: clang-format
  #       types_or: [c++, c, cuda]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  #  - repo: https://github.com/markdownlint/markdownlint
  #    rev: v0.13.0
  #    hooks:
  #      - id: markdownlint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
