add_subdirectory(flatbuffers)
add_subdirectory(shaders)
add_subdirectory(cursors)
add_subdirectory(textures)

function(hex_to_bytes in out_bytes out_total)
  string(REGEX MATCHALL "([A-Fa-f0-9][A-Fa-f0-9])" SEPARATED_HEX ${in})
  list(LENGTH SEPARATED_HEX num_hex_vals)
  foreach (hex IN LISTS SEPARATED_HEX)
      string(APPEND encoded_out "0x${hex}")
      math(EXPR counter "${counter}+1")
      math(EXPR len_minus_one "${num_hex_vals}-1")
      if(counter LESS ${len_minus_one})
        string(APPEND encoded_out ",")
      endif()
      if (counter GREATER 16)
          string(APPEND encoded_out "\n    ")
          set(counter 0)
      endif ()
  endforeach ()
  set(${out_bytes} ${encoded_out} PARENT_SCOPE)
  set(${out_total} ${num_hex_vals} PARENT_SCOPE)
endfunction()

function(pack_name_db db_name db_file )
  file(READ ${db_file} ${db_name}_BYTES HEX)
  hex_to_bytes(${${db_name}_BYTES} ${db_name}_BYTES ${db_name}_NUM_BYTES)
  set(${db_name}_NUM_BYTES ${${db_name}_NUM_BYTES} PARENT_SCOPE)
  set(${db_name}_BYTES ${${db_name}_BYTES} PARENT_SCOPE)
endfunction()

pack_name_db(PRT_FORENAMES_FEMALE "${CMAKE_CURRENT_SOURCE_DIR}/forenames_female.txt")
pack_name_db(PRT_FORENAMES_MALE "${CMAKE_CURRENT_SOURCE_DIR}/forenames_male.txt")
pack_name_db(PRT_SURNAMES "${CMAKE_CURRENT_SOURCE_DIR}/surnames.txt")

set(PRT_NAMESDB_IN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/names.h.in")
set(PRT_NAMESDB_OUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/prette/names.h")
configure_file(${PRT_NAMESDB_IN_FILE} ${PRT_NAMESDB_OUT_FILE})

add_library(prette-namesdb
  INTERFACE ${PRT_NAMESDB_OUT_FILE})
target_include_directories(prette-namesdb
  INTERFACE ${CMAKE_CURRENT_BINARY_DIR})
add_library(prette::namesdb ALIAS prette-namesdb)