function(hex_to_bytes in out_bytes out_total)
  string(REGEX MATCHALL "([A-Fa-f0-9][A-Fa-f0-9])" SEPARATED_HEX ${in})
  list(LENGTH SEPARATED_HEX num_hex_vals)
  foreach (hex IN LISTS SEPARATED_HEX)
      string(APPEND encoded_out "0x${hex}")
      math(EXPR counter "${counter}+1")
      math(EXPR len_minus_one "${num_hex_vals}-1")
      if(counter LESS ${len_minus_one})
        string(APPEND encoded_out ",")
      endif()
      if (counter GREATER 16)
          string(APPEND encoded_out "\n    ")
          set(counter 0)
      endif ()
  endforeach ()
  set(${out_bytes} ${encoded_out} PARENT_SCOPE)
  set(${out_total} ${num_hex_vals} PARENT_SCOPE)
endfunction()


function(add_cursor cursor_out cursor_image_file)
  file(READ ${cursor_image_file} ${cursor_out}_BYTES HEX)
  hex_to_bytes(${${cursor_out}_BYTES} ${cursor_out}_BYTES ${cursor_out}_NUM_BYTES)
  set(${cursor_out}_NUM_BYTES ${${cursor_out}_NUM_BYTES} PARENT_SCOPE)
  set(${cursor_out}_BYTES ${${cursor_out}_BYTES} PARENT_SCOPE)
endfunction()

add_subdirectory(bibata-modern-ice)