if(NOT PRT_BUILD_DATE)
  if(WIN32)
    execute_process(COMMAND "cmd" " /C date /T" OUTPUT_VARIABLE PRT_BUILD_DATE)
  else()
    execute_process(COMMAND "date" "+%d/%m/%Y" OUTPUT_VARIABLE PRT_BUILD_DATE)
    execute_process(COMMAND "date" "+%Y%m%d" OUTPUT_VARIABLE PRT_BUILD_DATE_FILESAFE)
  endif()
  string(REGEX REPLACE "(..)/(..)/..(..).*" "\\1/\\2/\\3" PRT_BUILD_DATE ${PRT_BUILD_DATE})
endif()