find_program(MOLD "mold")
if(MOLD)
  execute_process(COMMAND ${MOLD} --version
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    ERROR_QUIET
    OUTPUT_VARIABLE MOLD_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  string(REGEX MATCH "[0-9]+\.[0-9]+\.[0-9]+" MOLD_VERSION "${MOLD_VERSION}")

  list(APPEND MOLD_OPTS)
  message(STATUS "found mold v${MOLD_VERSION}: ${MOLD}")
endif()