set(SDL_GAMECONTROLLERDB_REPO "mdqinc/SDL_GameControllerDB")
set(SDL_GAMECONTROLLERDB_REF "7985423")
set(SDL_GAMECONTROLLERDB_BUILD_DIR ${CMAKE_BINARY_DIR})
file(DOWNLOAD "https://raw.githubusercontent.com/${SDL_GAMECONTROLLERDB_REPO}/${SDL_GAMECONTROLLERDB_REF}/gamecontrollerdb.txt"
  "${SDL_GAMECONTROLLERDB_BUILD_DIR}/gamecontrollerdb.txt")